# Generated by Django 4.0.1 on 2022-05-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
