# Generated by Django 4.0.1 on 2022-05-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
