# Generated by Django 4.0.1 on 2022-06-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0003_alter_signup_name_alter_signup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='age',
            field=models.TextField(max_length=50),
        ),
    ]
