# Generated by Django 4.0.1 on 2022-08-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0004_alter_signup_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
